#!/usr/bin/python3

'''
Usage:

	serratus_assembly_minimap2_qc.py hits.sam > report.tsv

The SAM file is generated by minimap2 by mapping assemblies
to complete Cov genomes, e.g.:

    minimap2 \
      -x map-pb \
      -t 8 \
      -a \
      -N 1 \
      ../minimap2_index/covref.mmi \
      catA-v3.fa \
      > hits.sam
'''

import sys

def ParseCigar(CIGAR):
	Clip = 0
	QL = 0
	M = 0

	assert CIGAR != "*"

	n = len(CIGAR)
	assert n > 0
	if not CIGAR[0].isdigit():
		print("CIGAR: not C[0].isdigit()", C, CIGAR)
		assert False
	assert CIGAR[n-1].isalpha()


	N = 0
	for c in CIGAR:
		if c.isdigit():
			N = N*10 + (ord(c) - ord('0'))
		elif c.isalpha() or c == '=':
			if c == 'S' or c == 'H':
				QL += N
				Clip += N
			elif c == 'M' or c == "=" or c == "I":
				M += N
				QL += N
			N = 0
		else:
			print("CIGAR: not letter or digit", C, CIGAR)
			assert False
	return QL, Clip, M

AssToMaxM = {}
AssToBestRec = {}

f = open(sys.argv[1])
for Line in f:
	if Line.startswith('@'):
		continue
	Fields = Line[:-1].split('\t')
	QueryLabel = Fields[0]
	Flags = int(Fields[1])
	RefLabel = Fields[2]
	Pos = Fields[3]
#	MAPQ = Fields[4]
	CIGAR = Fields[5]
#	RNEXT = Fields[6]
#	PNEXT = Fields[7]
	TLEN = int(Fields[8])
	# SEQ = Fields[9]
	Tags = Fields[11:]

	Ass = QueryLabel.split('.')[0]

	Diffs = None
	for Tag in Tags:
		if Tag.startswith("NM:i:"):
			Diffs = int(Tag[5:])
			break
	assert Diffs != None

	if (Flags & 0x10) == 0x10:
		Strand = "-"
	else:
		Strand = "+"

	QL, Clip, M = ParseCigar(CIGAR)
	LengthDiff = TLEN - QL - Clip
	PctId = 100.0 - (Diffs*100.0)/QL
	PctClip = (Clip*100.0)/QL

	if LengthDiff > -50 and LengthDiff < 50:
		Complete = "complete"
		Quality = "good"
	else:
		Complete = "partial"
		if Clip >= 1000:
			Quality = "misassembly"
		elif Clip >= 100:
			Quality = "clipped"
		else:
			assert Clip < 100
			Quality = "loclip"

	Rec = Ass
	Rec += "\t" + Quality
	Rec += "\t" + Complete
	Rec += "\t%.1f" % PctClip
	Rec += "\t%u" % QL
	Rec += "\t" + Strand
	Rec += "\t" + RefLabel
	Rec += "\t%u" % TLEN
	Rec += "\t%u" % Diffs
	Rec += "\t%.1f" % PctId
#	Rec += "\t" + CIGAR
	Rec += "\t%u" % Clip

	try:
		m = AssToMaxM[Ass]
	except:
		m = -1
	if M > m:
		AssToMaxM[Ass] = M
		AssToBestRec[Ass] = Rec

for Ass in list(AssToBestRec.keys()):
	Rec = AssToBestRec[Ass]
	print(Rec)
