FROM alpine:latest
# install all the dependencies
RUN 	apk add --update alpine-sdk && apk add wget git cmake unzip &&\
	wget http://eddylab.org/software/hmmer/hmmer-3.3.tar.gz && tar xzvf hmmer-3.3.tar.gz && cd hmmer-3.3/ &&\
	./configure && make -j4 && make install && cd easel && make install && cd ../../ &&\
	mkdir -p /serratus-data/serraplace && cd /serratus-data/serraplace && wget https://serratus-public.s3.amazonaws.com/pb/serraplace/reference/refpack.tar.gz && tar xzvf refpack.tar.gz &&\
	rm refpack.tar.gz && cd -