{
 "title": "Postgres Statement Stats",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Average Query Time [ms]",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_total_time_seconds[1m]) / rate(pg_stat_statements_calls[1m]) * 1000",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Total Query Time [s/s]",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_total_time_seconds[1m])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Statement Count [per second]",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_statements_calls[1m])",
     "legendFormat": "{{queryid}}"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pg_locks_count" }
   ]
  }
 ]
}