{
 "title": "Serratus",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instance", "label": "IP", "query": "label_values(instance)" },
   { "name": "interval", "query": "1m,2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Accessions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "scheduler_acc_state_count", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Blocks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "scheduler_block_state_count", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "DL/h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(scheduler_done_items_total{kind=\"dl\"}[$interval]) * 3600"
    }
   ]
  },
  {
   "title": "Align/h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(scheduler_done_items_total{kind=\"align\"}[$interval]) * 3600"
    }
   ]
  },
  {
   "title": "Acc/h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(scheduler_done_items_total{kind=\"merge\"}[$interval]) * 3600"
    }
   ]
  },
  {
   "title": "Block State",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scheduler_block_state_count", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "CPU Used Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (autoscaling_group) (sum without (mode) (rate(node_cpu_seconds_total{mode=~\"user|system\",instance=~\"$instance\"}[$interval])))",
     "legendFormat": "{{autoscaling_group}}"
    }
   ]
  },
  {
   "title": "Network Tx Total [B/s]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (autoscaling_group) (rate(node_network_transmit_bytes_total{instance=~\"$instance\",device=\"eth0\"}[$interval]))",
     "legendFormat": "{{autoscaling_group}}"
    }
   ]
  },
  {
   "title": "Network Rx Total [B/s]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (autoscaling_group) (rate(node_network_receive_bytes_total{instance=~\"$instance\",device=\"eth0\"}[$interval]))",
     "legendFormat": "{{autoscaling_group}}"
    }
   ]
  },
  {
   "title": "Accession State",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scheduler_acc_state_count", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Memory Used Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (autoscaling_group) ( 1 - (node_memory_MemAvailable_bytes{instance=~\"$instance\"}/node_memory_MemTotal_bytes{instance=~\"$instance\"} ) )",
     "legendFormat": "{{autoscaling_group}}"
    }
   ]
  },
  {
   "title": "Disk Used Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (autoscaling_group) (1- (node_filesystem_avail_bytes{instance=~\"$instance\"} / node_filesystem_size_bytes{instance=~\"$instance\"}))",
     "legendFormat": "{{autoscaling_group}}"
    }
   ]
  }
 ]
}