{
 "title": "Serratus - ASG",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "instance", "label": "IP", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Accessions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "scheduler_accesion_state", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Blocks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 12, "y": 0 },
   "targets": [
    { "expr": "scheduler_block_state", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Blocks / min",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "expr": "60 * rate(scheduler_block_state{state=\"done\"}[5m])"
    }
   ]
  },
  {
   "title": "Accession State",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scheduler_accesion_state", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Block State",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scheduler_block_state", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "CPU Used Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (autoscaling_group) (sum without (mode) (rate(node_cpu_seconds_total{mode=~\"user|system\",instance=~\"$instance\"}[15s])))",
     "legendFormat": "{{autoscaling_group}}"
    }
   ]
  },
  {
   "title": "Memory Used Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (autoscaling_group) ( 1 - (node_memory_MemAvailable_bytes{instance=~\"$instance\"}/node_memory_MemTotal_bytes{instance=~\"$instance\"} ) )",
     "legendFormat": "{{autoscaling_group}}"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (autoscaling_group) (rate(node_disk_read_bytes_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{autoscaling_group}}"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (autoscaling_group) (rate(node_disk_written_bytes_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{autoscaling_group}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (autoscaling_group) (rate(node_network_transmit_bytes_total{instance=~\"$instance\",device=\"eth0\"}[5m]))",
     "legendFormat": "{{autoscaling_group}}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (autoscaling_group) (rate(node_network_receive_bytes_total{instance=~\"$instance\",device=\"eth0\"}[5m]))",
     "legendFormat": "{{autoscaling_group}}"
    }
   ]
  },
  {
   "title": "Disk Used Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (autoscaling_group) (1- (node_filesystem_avail_bytes{instance=~\"$instance\"} / node_filesystem_size_bytes{instance=~\"$instance\"}))",
     "legendFormat": "{{autoscaling_group}}"
    }
   ]
  }
 ]
}