{
 "title": "Serratus Scheduler",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "asg", "query": "label_values(asg)" }
  ]
 },
 "panels": [
  {
   "title": "Accession State",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scheduler_acc_state_count", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Block State",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scheduler_block_state_count", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "serratus-$asg Autoscaling",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "repeat": "asg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "asg_desired_size{asg=~\"$asg\"}",
     "legendFormat": "serratus-{{asg}} (desired)"
    },
    {
     "expr": "asg_virt_size{asg=~\"$asg\"}",
     "legendFormat": "serratus-{{asg}} (actual)"
    },
    {
     "expr": "sum by (autoscaling_group) (up{autoscaling_group=~\"serratus-$asg\"})",
     "legendFormat": "{{autoscaling_group}} (up)"
    }
   ]
  },
  {
   "title": "serratus-$asg Autoscaling",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "asg_desired_size{asg=~\"$asg\"}",
     "legendFormat": "serratus-{{asg}} (desired)"
    },
    {
     "expr": "asg_virt_size{asg=~\"$asg\"}",
     "legendFormat": "serratus-{{asg}} (actual)"
    },
    {
     "expr": "sum by (autoscaling_group) (up{autoscaling_group=~\"serratus-$asg\"})",
     "legendFormat": "{{autoscaling_group}} (up)"
    }
   ]
  },
  {
   "title": "serratus-$asg Autoscaling",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "asg_desired_size{asg=~\"$asg\"}",
     "legendFormat": "serratus-{{asg}} (desired)"
    },
    {
     "expr": "asg_virt_size{asg=~\"$asg\"}",
     "legendFormat": "serratus-{{asg}} (actual)"
    },
    {
     "expr": "sum by (autoscaling_group) (up{autoscaling_group=~\"serratus-$asg\"})",
     "legendFormat": "{{autoscaling_group}} (up)"
    }
   ]
  },
  {
   "title": "Average Request Latency [ms]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(scheduler_request_latency_seconds_sum[1m]) / rate(scheduler_request_latency_seconds_count[1m]) * 1000.",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Total Request Time [s/s]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(scheduler_request_latency_seconds_sum[1m])",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Request Count [per second]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(scheduler_request_latency_seconds_count[1m])",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  }
 ]
}