FROM ubuntu

RUN apt-get update -yq
RUN apt-get install -yqq python3-pip

ADD flaskr/ /opt/flaskr
WORKDIR /opt/

RUN pip3 install flask sqlalchemy gunicorn

# Run Python in UTF-8 mode
ENV FLASK_APP=flaskr
ENV FLASK_ENV=development
ENV LANG=C.UTF-8

# TODO: Implement a way to ADD jobs to the server
#       Or some persistence?
RUN bash -c 'for i in $(seq 1 10); do echo a,a,a,a >> job_list.csv; done'
RUN flask init-db job_list.csv

# Do NOT enable multithreading here, as the underlying app is
# thread-unsafe.
CMD gunicorn 'flaskr:create_app()' --bind '0.0.0.0:8000'

