{
 "title": "New dashboard 2",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Block State",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scheduler_block_state", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Accession State",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scheduler_accesion_state", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "CPU Used Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (sum without (mode) (rate(node_cpu_seconds_total{mode=~\"user|system\"}[15s])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Used Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1-(node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Used Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)",
     "legendFormat": "{{instance}} - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU Credits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "CPUCreditBalance",
     "namespace": "AWS/EC2",
     "period": "300",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "CPUSurplusCreditBalance",
     "namespace": "AWS/EC2",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}