{
 "title": "Instance Stats 2",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "prefix",
    "label": "Bucket Prefix",
    "query": "full,prefix-fq-blocks,prefix-bam-blocks,prefix-out"
   }
  ]
 },
 "panels": [
  {
   "title": "Accessions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "scheduler_accesion_state", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Blocks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 12, "y": 0 },
   "targets": [
    { "expr": "scheduler_block_state", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Blocks / min",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "expr": "60 * rate(scheduler_block_state{state=\"done\"}[5m])"
    }
   ]
  },
  {
   "title": "Accession State",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scheduler_accesion_state", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Block State",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scheduler_block_state", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "CPU Used Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (sum without (mode) (rate(node_cpu_seconds_total{mode=~\"user|system\"}[15s])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Used Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1-(node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Used Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)",
     "legendFormat": "{{instance}} - {{mountpoint}}"
    }
   ]
  }
 ]
}